language: julia
os:
- linux
julia:
- 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_script:
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'
script:
- julia --color=yes build_tarballs.jl

deploy:
  provider: releases
  api_key:
    secure: JZYiG0xSrT/Wkh4yokkz92dFkV6Aq857wqisKu+qytMJoZcepFe2XsW8N3YIEg0fTnNUwiFYXtUUzTU83r5ppIhPeY1iqOTrGOFfzjmJh8NMVet0re2SSVChqc/T7VdO89+gNONz6ByuOECIk5lbcHAaWWZTDcpg9ILlrv4ffTKSZ1IhflVfEuu0+UKrHUJvV9PYoNZ/DPDisHvlMm+ZDg564EFsR7sqC8cAHW2/fTUwxYIVboks89kQhT4WeVV4VxyokbX7OfLpBp+1zXC8ZI5Dq958Bw9uiirQgIkfr2MnOExHe/uNDzdcTC5IOsjVTwR9+Nr3nFYjlP9XBH71XlZtTdyKC1htUSQLuHrxUEckVZWtI9lXM2i1V8c9PTSam5A2hw+IzGEH3L+OCNR6/O1P6KHAM51HDhnRjj1hbSx74TH/+xsYGWckxJ0Tqhkwe4NZhGVKg/K7emAf4+1WD51BKVCPR/quCepJPvw7P6gU2/6qY7UoDykVQZdi54E0lzS5bs1/pzDjALHCzxW1dlp/Zswq9sJL+YZ8pWsLoT8JDvew292L1E2aqTzZAmvrD48KyhFuWiNWRSsah0DfiwxOTnmHYhchAXO5VphnNKapWDpAjYNMEn9YTgRghCcUmfhW9u2hRvoX7D7XC9Sc5SdjaDnZL4M+iWbrLu3ztWI=
  file: products/*
  skip_cleanup: true
  file_glob: true
  on:
    repo: saschatimme/CDDLibBuilder
    tags: true
